# Generated by Django 2.2.3 on 2019-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0003_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
